const store=window.OvertimeStore
const roles=[['hero','勇者','#ffd4a7','#111318','#2b74d1'],['demon','大魔王','#c35b5c','#1a121c','#7d2ed1'],['goblin','哥布林','#6fca3b','#26381f','#8b5a2b'],['princess','公主','#ffd7b2','#f0c85b','#e36eb0'],['mage','法师','#d9b7ff','#25213c','#5f49d8'],['hunter','猎人','#f2c493','#5f3d24','#2f9b52'],['elf','精灵','#ffd7af','#d8e36b','#3cb86d'],['knight','骑士','#cfd8e3','#3d485c','#497ccf'],['dwarf','矮人','#f0c495','#b65c2b','#4b74a9']].map(v=>({key:v[0],name:v[1],skin:v[2],hair:v[3],cloth:v[4]}))
const types=['设计','渲染','修改','会议','其他'], levelTitles=[['摸鱼见习生',0,49],['工位巡逻员',50,99],['咖啡续命师',100,199],['表格搬砖侠',200,399],['键盘小怪兽',400,599],['会议幸存者',600,899],['需求驯兽师',900,1199],['深夜副本王',1200,1599],['方案爆改侠',1600,1999],['甲方终结者',2000,2499],['通宵守门人',2500,3199],['加班大魔王',3200,1/0]]
let page='login', selectedRole=roles[0], selectedType='设计', currentMonth=new Date(), confirmAction=null, confirmBusyText='处理中...', exportScope='week'
const $=id=>document.getElementById(id), uid=p=>p+'_'+Date.now()+'_'+Math.random().toString(16).slice(2), pad=n=>String(n).padStart(2,'0'), fmt=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`, cnDate=d=>`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日`, week=d=>['周日','周一','周二','周三','周四','周五','周六'][d.getDay()], esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))
const users=()=>store.users(), saveUsers=v=>store.saveUsers(v), currentUser=()=>store.currentUser(), allRecords=()=>store.allRecords(), records=()=>store.recordsForCurrentUser(), saveRecords=v=>store.saveRecords(v), sum=a=>Math.round(a.reduce((t,r)=>t+Number(r.duration||0),0)*100)/100
async function runSync(fn,done){try{await fn();if(done)done()}catch(e){showToast(e.message||'飞书保存失败')}}
function duration(s,e){if(!s||!e)return 0;const [sh,sm]=s.split(':').map(Number),[eh,em]=e.split(':').map(Number);let m=eh*60+em-sh*60-sm;if(m<0)m+=1440;return Math.round(m/60*100)/100}
function monday(d){d=new Date(d);const day=d.getDay()||7;d.setDate(d.getDate()-day+1);d.setHours(0,0,0,0);return d}
function sameWeek(v,b=new Date()){const d=new Date(v),s=monday(b),e=new Date(s);e.setDate(s.getDate()+7);return d>=s&&d<e}
function monthDays(y,m){return Array.from({length:new Date(y,m+1,0).getDate()},(_,i)=>new Date(y,m,i+1))}
function titleFromExp(exp){exp=Math.max(0,Number(exp||0));return (levelTitles.find(x=>exp>=x[1]&&exp<=x[2])||levelTitles.at(-1))[0]}
function levelFromExp(exp){exp=Math.max(0,Number(exp||0));return levelTitles.findIndex(x=>exp>=x[1]&&exp<=x[2])+1||12}
function levelProgress(exp){const i=levelFromExp(exp)-1,t=levelTitles[i];return t[2]===Infinity?100:Math.max(0,Math.min(100,Math.round((exp-t[1])/(t[2]-t[1]+1)*100)))}
function userTotalInMode(id,mode,base=new Date()){const u=users().find(x=>x.id===id);if(u&&currentUser()?.id!==id){if(mode==='day')return u.todayHours||0;if(mode==='week')return u.weekHours||0;if(mode==='month')return u.monthHours||0;if(mode==='year')return u.yearHours||0;return u.totalHours||0}const rs=allRecords().filter(r=>r.userId===id);if(mode==='day')return sum(rs.filter(r=>r.date===fmt(base)));if(mode==='week')return sum(rs.filter(r=>sameWeek(r.date,base)));if(mode==='month')return sum(rs.filter(r=>{const d=new Date(r.date);return d.getFullYear()===base.getFullYear()&&d.getMonth()===base.getMonth()}));if(mode==='year')return sum(rs.filter(r=>new Date(r.date).getFullYear()===base.getFullYear()));return sum(rs)}
function totalExpForUser(id){const u=users().find(x=>x.id===id);if(u&&currentUser()?.id!==id)return Math.round(u.totalExp||0);return u&&u.expOverride!=null?Math.max(0,Math.round(+u.expOverride||0)):Math.round(userTotalInMode(id,'all')*10)}
function totals(b=new Date()){const rs=records();return{day:sum(rs.filter(r=>r.date===fmt(b))),week:sum(rs.filter(r=>sameWeek(r.date,b))),month:sum(rs.filter(r=>{const d=new Date(r.date);return d.getFullYear()===b.getFullYear()&&d.getMonth()===b.getMonth()})),year:sum(rs.filter(r=>new Date(r.date).getFullYear()===b.getFullYear()))}}
function displayName(u){return u?u.isAdmin?esc(u.username):`${esc(u.username)} <span class="title-badge">@${esc(titleFromExp(totalExpForUser(u.id)))}@</span>`:''}
function rect(x,y,w,h,c){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${c}"/>`}
function sprite(key){
const r=roles.find(x=>x.key===key)||roles[0],p=[],R=rect
const skin=r.skin,hair=r.hair,cloth=r.cloth,black='#111318',line='#4d2b27'
const face=(x=30,y=24,w=28,h=30)=>p.push(R(x,y,w,h,skin),R(x+7,y+12,4,5,black),R(x+w-12,y+12,4,5,black),R(x+12,y+24,8,3,line))
const torso=(x=26,y=54,w=36,h=28,c=cloth)=>p.push(R(x,y,w,h,c),R(x+4,y+14,w-8,5,'rgba(255,255,255,.2)'),R(x-5,y+24,14,7,'#19243a'),R(x+w-9,y+24,14,7,'#19243a'))
if(key==='hero'){p.push(R(8,28,7,35,'#dadfe8'),R(5,25,13,7,'#9ea7b5'),R(14,51,9,8,'#8a5a22'),R(61,44,12,20,'#8b2f22'),R(23,20,42,13,hair),R(25,16,9,8,hair),R(39,15,9,7,hair),R(54,16,8,8,hair));face(28,28,32,28);p.push(R(24,50,42,10,'#c9322f'));torso(25,58,38,22,'#1f6dde');p.push(R(34,63,20,10,'#e8b44e'),R(38,62,12,12,'#f4d35f'),R(18,54,13,13,'#edf4ff'),R(21,57,7,7,'#5a6984'))}
else if(key==='princess'){p.push(R(28,11,32,9,'#ffd84e'),R(31,6,6,8,'#ffd84e'),R(42,4,6,10,'#ffd84e'),R(53,6,6,8,'#ffd84e'),R(23,22,42,33,'#f2c85b'),R(21,31,9,28,'#f2c85b'),R(58,31,9,28,'#f2c85b'));face(30,28,28,28);torso(25,57,38,25,'#df61b7');p.push(R(31,56,26,7,'#ff90cf'),R(39,60,10,12,'#ffe28a'))}
else if(key==='hunter'){p.push(R(19,15,50,9,'#5b371f'),R(25,9,35,10,'#6d4729'),R(62,22,7,40,'#7a4b20'),R(66,25,3,33,'#efd58a'),R(17,31,10,8,skin),R(61,31,10,8,skin));face(28,25,32,31);torso(25,56,38,26,'#2d9a55');p.push(R(30,54,28,7,'#53c071'),R(34,63,20,6,'#815326'),R(14,57,12,5,'#d8b16b'))}
else if(key==='demon'){p.push(R(18,10,9,17,'#ffe06b'),R(61,10,9,17,'#ffe06b'),R(22,18,9,10,'#b21f3a'),R(57,18,9,10,'#b21f3a'),R(21,21,46,14,hair),R(24,28,40,29,skin));p.push(R(31,40,6,5,black),R(51,40,6,5,black),R(39,49,12,4,'#74342d'),R(24,56,40,26,cloth),R(14,54,13,21,'#4f1f7d'),R(61,54,13,21,'#4f1f7d'),R(31,58,26,8,'#ac53ff'),R(39,62,10,11,'#f25353'))}
else if(key==='goblin'){p.push(R(10,31,17,9,skin),R(61,31,17,9,skin),R(21,18,46,12,'#26381f'),R(25,24,38,32,skin));p.push(R(31,38,6,5,black),R(51,38,6,5,black),R(39,48,10,4,'#243018'),R(34,54,5,7,'#f5e7b8'),R(50,54,5,7,'#f5e7b8'));torso(25,58,38,24,'#8b5a2b');p.push(R(31,60,26,7,'#c79a58'),R(16,55,10,22,'#566b28'),R(62,55,10,22,'#566b28'))}
else if(key==='mage'){p.push(R(26,8,35,8,'#f6d75e'),R(30,0,26,10,'#4d3ac9'),R(21,16,46,10,'#4d3ac9'),R(23,25,42,10,hair));face(29,30,30,28);torso(23,58,42,24,cloth);p.push(R(15,50,5,32,'#8a5a22'),R(11,45,13,8,'#f6d75e'),R(32,59,24,8,'#7d6cff'),R(38,63,12,13,'#f6d75e'))}
else if(key==='elf'){p.push(R(13,31,14,8,skin),R(61,31,14,8,skin),R(22,20,44,12,hair),R(25,16,38,8,'#d9e66a'));face(28,29,32,29);torso(25,58,38,24,'#40b96d');p.push(R(33,56,22,7,'#8ee08f'),R(15,55,10,22,'#9ddf74'),R(63,55,10,22,'#9ddf74'))}
else if(key==='knight'){p.push(R(22,17,44,11,'#cbd4df'),R(18,28,52,17,'#9ba8ba'),R(24,29,40,9,'#e7edf4'));face(30,38,28,18);p.push(R(34,43,5,4,black),R(50,43,5,4,black),R(39,52,10,3,line),R(23,56,42,26,'#497ccf'),R(16,53,13,24,'#b7c2d0'),R(62,53,13,24,'#b7c2d0'),R(32,58,24,7,'#d9e4f0'),R(38,62,12,12,'#f2c94c'))}
else{p.push(R(21,19,46,12,hair));face(28,28,32,29);torso(25,58,38,24,cloth);p.push(R(30,50,28,16,'#d17a36'),R(16,55,11,21,'#4b74a9'),R(62,55,11,21,'#4b74a9'),R(60,41,16,5,'#7a4b20'),R(70,35,5,13,'#bfc7d5'))}
return `<svg class="pixel-sprite" viewBox="0 0 88 88" shape-rendering="crispEdges">${p.join('')}</svg>`}
async function ensureAdminAccount(){}
function showToast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.classList.remove('show'),1400)}
function installPressFeedback(){if(window.__pressFeedbackReady)return;window.__pressFeedbackReady=true;const clear=()=>document.querySelectorAll('.pressing').forEach(x=>x.classList.remove('pressing'));document.addEventListener('pointerdown',e=>{const b=e.target.closest('button');if(b){clear();b.classList.add('pressing')}});['pointerup','pointercancel','pointerleave','blur'].forEach(v=>document.addEventListener(v,clear,true));document.addEventListener('click',()=>setTimeout(clear,120),true)}
function setBusyButton(btn,text){if(!btn)return()=>{};const old=btn.textContent;btn.disabled=true;btn.classList.add('busy');btn.textContent=text;return()=>{btn.disabled=false;btn.classList.remove('busy');btn.textContent=old}}
function askConfirm(t,m,fn,busy='处理中...'){$('confirmTitle').textContent=t;$('confirmMessage').textContent=m;confirmAction=fn;confirmBusyText=busy;$('confirmMask').classList.add('show')}function closeConfirm(){confirmAction=null;$('confirmMask').classList.remove('show')}async function confirmYes(btn){const fn=confirmAction;if(typeof fn!=='function')return closeConfirm();const done=setBusyButton(btn,confirmBusyText);try{await fn();closeConfirm()}catch(e){done();showToast(e.message||'操作失败')}}
async function boot(){installPressFeedback();renderLoading();await store.init();await ensureAdminAccount();renderTypeGrid();if(currentUser())page='home';render();$('fStart').addEventListener('input',updateDurationPreview);$('fEnd').addEventListener('input',updateDurationPreview);document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>{page=b.dataset.page;render()}))}
function renderLoading(){$('main').innerHTML=`<section class="panel auth"><h1>同步数据中</h1><p class="muted">正在读取飞书多维表格里的账号和加班记录。</p></section>`}
function render(){const u=currentUser();$('nav').classList.toggle('hidden',!u);document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(!u)return page==='register'?renderRegister():renderLogin();({home:renderHome,calendar:renderCalendar,stats:renderStats,leaderboard:renderLeaderboard,profile:renderProfile}[page]||renderHome)()}
function renderLogin(){$('main').innerHTML=`<section class="panel auth"><h1>开始冒险</h1><p class="muted">登录角色，进入你的加班副本。</p>${store.lastError()?`<p class="error">${esc(store.lastError())}</p>`:''}<label>用户名</label><input id="loginName" placeholder="请输入用户名"><label>密码</label><input id="loginPass" type="password" placeholder="请输入密码"><p class="error" id="loginError"></p><button class="btn full" onclick="login(this)">开始冒险</button><button class="btn gray full" onclick="page='register';render()">创建角色 / 注册</button></section>`}
async function saveGithubToken(){showToast('正在同步飞书数据');await store.init();await ensureAdminAccount();render();showToast('同步完成')}
function avatarGridHtml(){return roles.map((r,i)=>`<button type="button" class="avatar-card ${selectedRole.key===r.key?'active':''}" onclick="pickRole(${i})"><div class="portrait-wrap">${sprite(r.key)}</div><small>${r.name}</small></button>`).join('')}function pickRole(i){selectedRole=roles[i];$('avatarGrid').innerHTML=avatarGridHtml()}
function renderRegister(){$('main').innerHTML=`<section class="panel auth"><h1>创建角色</h1><p class="muted">注册时选择 8bit 像素角色头像。</p><label>用户名</label><input id="regName" placeholder="例如：设计部勇者"><label>密码</label><input id="regPass" type="password" placeholder="设置密码"><label>确认密码</label><input id="regConfirm" type="password" placeholder="再次输入密码"><label>角色头像</label><div class="avatars" id="avatarGrid">${avatarGridHtml()}</div><p class="error" id="regError"></p><button class="btn full" onclick="register(this)">创建角色</button><button class="btn gray full" onclick="page='login';render()">返回登录</button></section>`}
async function login(btn){const n=$('loginName').value.trim(),p=$('loginPass').value,done=setBusyButton(btn,'登录中...');try{await store.login(n,p);page='home';render();store.syncRemote().then(()=>{if(currentUser()){render();showToast('飞书数据已同步')}}).catch(e=>showToast(e.message||'飞书同步失败'))}catch(e){done();$('loginError').textContent=e.message||'账号或密码错误'}}
async function register(btn){const n=$('regName').value.trim(),p=$('regPass').value,c=$('regConfirm').value;if(!n)return $('regError').textContent='请输入用户名';if(!p)return $('regError').textContent='请输入密码';if(p!==c)return $('regError').textContent='两次密码不一致';const done=setBusyButton(btn,'创建中...'),u={id:uid('user'),username:n,password:p,role:selectedRole.name,roleKey:selectedRole.key,createdAt:new Date().toISOString(),expOverride:null};try{await store.register(u);page='home';render();showToast('已创建并同步')}catch(e){done();showToast(e.message||'飞书保存失败')}}
function seed(id){const now=new Date(),next=allRecords(),samples=[[0,'18:30','21:00','设计','产品方案修改'],[-2,'20:00','23:30','修改','临时调整'],[-5,'19:30','22:30','渲染','场景图渲染']];samples.forEach(x=>{const d=new Date(now);d.setDate(now.getDate()+x[0]);next.push({id:uid('rec'),userId:id,date:fmt(d),startTime:x[1],endTime:x[2],duration:duration(x[1],x[2]),type:x[3],remark:x[4],createdAt:new Date().toISOString()})});saveRecords(next)}
function statIconClass(l){return l==='今日'||l==='日均'?'clock':l==='本周'?'calendar':l==='本月'?'coin':'trophy'}
function statCard(l,v){return `<section class="stat"><span class="label">${l}</span><span class="stat-icon ${statIconClass(l)}"></span><span class="value">${v}<small>h</small></span><span class="exp">EXP +${Math.round(v*10)}</span></section>`}
function recordList(list){return list.length?`<div class="record-list">${list.map(r=>`<div class="record"><div><div class="time-line">${r.startTime}-${r.endTime}</div><div class="record-note">${esc(r.type)} · ${esc(r.remark||'无备注')}</div></div><div class="record-side"><div class="hours">${r.duration}h</div><div class="action-row"><button class="btn small" onclick="openSheet('${esc(r.date)}','${esc(r.id)}')">编辑</button><button class="btn small red" onclick="requestDelete('${esc(r.id)}')">删除</button></div></div></div>`).join('')}</div>`:`<div class="empty">暂无加班记录</div>`}
function renderHome(){const u=currentUser(),now=new Date(),t=totals(now),today=fmt(now),todayList=records().filter(r=>r.date===today);$('main').innerHTML=`<div class="stack"><section class="panel hero-panel"><div class="portrait-wrap">${sprite(u.roleKey)}</div><div class="hero-info"><h1>你好，${displayName(u)}</h1><div class="date-row">${cnDate(now)} ${week(now)}</div><div class="job-row">职业：${esc(u.role||'勇者')} · LV.${levelFromExp(totalExpForUser(u.id))} · EXP ${totalExpForUser(u.id)}</div></div></section><section class="stats">${statCard('今日',t.day)}${statCard('本周',t.week)}${statCard('本月',t.month)}${statCard('本年',t.year)}</section><section class="panel"><div class="section-head"><h2>今日记录</h2><span class="count">${todayList.length} 条记录</span></div>${recordList(todayList)}<button class="btn full" onclick="openSheet('${today}')">＋ 添加今日加班</button></section></div>`}
function requestDelete(id){const r=allRecords().find(v=>v.id===id);if(!r)return showToast('没有找到记录');askConfirm('确认删除？',`即将删除 ${r.date} ${r.duration}h 记录。`,async()=>{await store.deleteRecord(id);render();showToast('已删除并同步')},'删除中...')}
function renderCalendar(){const y=currentMonth.getFullYear(),m=currentMonth.getMonth(),mode=store.viewMode(),addDate=fmt(new Date(y,m,1)),total=sum(records().filter(r=>{const d=new Date(r.date);return d.getFullYear()===y&&d.getMonth()===m}));$('main').innerHTML=`<div class="stack"><section class="panel"><div class="month-main"><button class="arrow" onclick="moveMonth(-1)">‹</button><div class="month-title"><h2>${y}年${m+1}月</h2><p class="muted">本月 ${total}h · ${titleFromExp(total*10)}</p></div><button class="arrow" onclick="moveMonth(1)">›</button></div><div class="view-switch"><button class="${mode==='calendar'?'active':''}" onclick="setView('calendar')">月历视图</button><button class="${mode==='list'?'active':''}" onclick="setView('list')">列表视图</button></div></section><button class="btn green full add-short" onclick="openSheet('${addDate}')">＋ 添加</button>${mode==='calendar'?calendarHtml(y,m):listHtml(y,m)}</div>`}
function moveMonth(n){currentMonth=new Date(currentMonth.getFullYear(),currentMonth.getMonth()+n,1);renderCalendar()}function setView(m){store.setViewMode(m);renderCalendar()}
function calendarHtml(y,m){const days=monthDays(y,m),off=days[0].getDay()===0?6:days[0].getDay()-1,cells=[...Array(off).fill(null),...days];return `<section class="panel"><div class="week-row">${['一','二','三','四','五','六','日'].map(v=>`<span>${v}</span>`).join('')}</div><div class="calendar-grid">${cells.map(d=>{if(!d)return `<div class="day empty-cell"></div>`;const date=fmt(d),dayRecords=records().filter(r=>r.date===date),total=sum(dayRecords);return `<button class="day ${total?'has':''}" onclick="${total?`showDayRecords('${date}')`:`openSheet('${date}')`}"><span>${d.getDate()}</span><br><small>${total?total+'h':''}</small></button>`}).join('')}</div></section>`}
function showDayRecords(date){const rs=records().filter(r=>r.date===date),total=sum(rs),d=new Date(date);$('main').innerHTML=`<div class="stack"><section class="panel"><div class="section-head"><h2>${d.getMonth()+1}月${d.getDate()}日</h2><span class="count">${total}h · ${rs.length} 条记录</span></div>${recordList(rs)}<button class="btn green full add-short" onclick="openSheet('${date}')">＋ 添加</button><button class="btn gray full" onclick="renderCalendar()">返回日历</button></section></div>`}
function listHtml(y,m){const items=monthDays(y,m).map(d=>({d,date:fmt(d),rs:records().filter(r=>r.date===fmt(d))})).map(x=>({...x,total:sum(x.rs)})).filter(x=>x.total);return items.length?`<div class="stack">${items.map(x=>`<section class="panel"><div class="section-head"><h2>${x.d.getMonth()+1}月${x.d.getDate()}日</h2><span class="count">${x.total}h</span></div>${recordList(x.rs)}</section>`).join('')}</div>`:`<section class="panel"><div class="empty">本月暂无加班记录。</div></section>`}
function renderStats(){const now=new Date(),t=totals(now),rs=records(),days=monthDays(now.getFullYear(),now.getMonth()).map(d=>({label:`${d.getMonth()+1}/${d.getDate()}`,total:sum(rs.filter(r=>r.date===fmt(d)))})).filter(x=>x.total),months=Array.from({length:12},(_,i)=>({label:`${i+1}月`,total:sum(rs.filter(r=>{const d=new Date(r.date);return d.getFullYear()===now.getFullYear()&&d.getMonth()===i}))})).filter(x=>x.total);$('main').innerHTML=`<div class="stack"><section class="panel"><div class="section-head"><h2>统计中心</h2><span class="count">${now.getFullYear()}年度</span></div><p class="muted">本月称号：${titleFromExp(t.month*10)}</p><p class="muted">年度称号：${titleFromExp(t.year*10)}</p></section><section class="stats">${statCard('本周',t.week)}${statCard('本月',t.month)}${statCard('本年',t.year)}${statCard('日均',days.length?Math.round(t.month/days.length*100)/100:0)}</section>${barPanel('本月能量条',days,18)}${barPanel('年度月度统计',months,5)}</div>`}
function barPanel(title,rows,scale){return `<section class="panel"><div class="section-head"><h2>${title}</h2></div><div class="bars">${rows.length?rows.map(v=>`<div class="bar-row"><span>${v.label}</span><div class="bar"><i style="width:${Math.min(100,v.total*scale)}%"></i></div><b>${v.total}h</b></div>`).join(''):'<div class="empty">暂无数据</div>'}</div></section>`}
async function renderLeaderboard(){const mode=store.rankMode(),tabs=[['day','日排'],['week','周排'],['month','月排'],['year','年排'],['level','等级']];let list=[];try{list=await store.leaderboardRows(mode)}catch(e){showToast(e.message||'排行同步失败')}const rows=list.filter(u=>!u.isAdmin).map(u=>{const h=mode==='day'?u.todayHours:mode==='week'?u.weekHours:mode==='month'?u.monthHours:mode==='year'?u.yearHours:u.level,all=u.totalHours,exp=u.totalExp,lv=u.level||levelFromExp(exp);return{u,h,all,exp,lv,title:u.title||titleFromExp(exp),progress:levelProgress(exp)}}).sort((a,b)=>mode==='level'?b.lv-a.lv||b.exp-a.exp:b.h-a.h||b.exp-a.exp);$('main').innerHTML=`<div class="stack"><section class="panel"><div class="section-head"><h2>排名榜</h2><button class="icon-btn refresh-btn" onclick="refreshRank()" aria-label="刷新排行榜"><span>↻</span><em>刷新</em></button></div><div class="rank-tabs">${tabs.map(t=>`<button class="${mode===t[0]?'active':''}" onclick="setRankMode('${t[0]}')">${t[1]}</button>`).join('')}</div><p class="muted">排行榜优先显示本地数据，点刷新后拉取最新汇总</p></section><section class="panel"><div class="rank-list">${rows.map((r,i)=>rankRow(r,i,mode)).join('')||'<div class="empty">暂无用户数据</div>'}</div></section></div>`}
function rankRow(r,i,mode){return `<div class="rank-row"><div class="rank-no">${i+1}</div><div>${sprite(r.u.roleKey)}</div><div class="rank-info"><span class="rank-name">${esc(r.u.username)}</span><span class="rank-role">${esc(r.u.role||'勇者')}</span><span class="rank-title">${esc(r.title)}</span><div class="muted">累计 ${r.all}h</div><div class="level-meter"><i style="width:${r.progress}%"></i></div></div><div class="rank-score"><b>${mode==='level'?'LV.'+r.lv:r.h+'h'}</b><span>EXP ${r.exp}</span></div></div>`}
function setRankMode(m){store.setRankMode(m);renderLeaderboard()}
async function refreshRank(){showToast('正在刷新排行榜');try{await store.refreshLeaderboard(store.rankMode());await renderLeaderboard();showToast('排行榜已更新')}catch(e){showToast(e.message||'排行榜刷新失败')}}
function renderProfile(){const u=currentUser(),rs=records();$('main').innerHTML=`<div class="stack"><section class="panel hero-panel"><div class="portrait-wrap">${sprite(u.roleKey)}</div><div class="hero-info"><h1>${u.isAdmin?esc(u.username):displayName(u)}${u.isAdmin?'<span class="admin-badge">ADMIN</span>':''}</h1><div class="date-row">职业：${esc(u.role||'勇者')}</div><div class="job-row">本地记录：${rs.length} 条 · LV.${levelFromExp(totalExpForUser(u.id))} · EXP ${totalExpForUser(u.id)}</div></div></section><section class="panel menu"><button onclick="exportData()">导出数据 <span>›</span></button><button onclick="requestClear()">清空当前用户记录 <span>›</span></button><button onclick="logout()">退出登录 <span>›</span></button></section>${u.isAdmin?renderAdminPanel():''}</div>`}
function renderAdminPanel(){const list=users().filter(u=>!u.isAdmin);return `<section class="panel"><div class="section-head"><h2>管理员面板</h2><span class="count">${list.length} 个普通用户</span></div><p class="muted">管理员账户为隐藏账户：owenlu / 110110。管理员不参与排行和统计。</p><div class="admin-list">${list.map(adminUserRow).join('')||'<div class="empty">暂无普通用户</div>'}</div></section>`}
function adminUserRow(u){const exp=totalExpForUser(u.id),hours=userTotalInMode(u.id,'all');return `<div class="admin-row"><div>${sprite(u.roleKey)}</div><div><b>${displayName(u)}</b><div class="muted">${esc(u.role)} · ${hours}h · LV.${levelFromExp(exp)} · EXP ${exp}</div><div class="admin-controls"><input id="adminExp_${esc(u.id)}" type="number" min="0" value="${exp}"><button class="btn" onclick="adminSaveExp('${esc(u.id)}')">保存EXP</button><button class="btn red" onclick="adminDeleteUser('${esc(u.id)}')">删除</button></div></div></div>`}
function adminSaveExp(id){if(!currentUser()?.isAdmin)return showToast('没有管理员权限');const v=Math.max(0,Math.round(+$(`adminExp_${id}`).value||0)),u=users().find(u=>u.id===id);if(!u)return showToast('没有找到用户');runSync(()=>store.saveUser({...u,expOverride:v}),()=>{renderProfile();showToast('EXP 已更新并同步')})}
function adminDeleteUser(id){if(!currentUser()?.isAdmin)return showToast('没有管理员权限');const u=users().find(u=>u.id===id);askConfirm('确认删除账户？',`即将删除用户 ${u?.username||''} 及全部记录。`,()=>runSync(()=>store.deleteUser(id),()=>{renderProfile();showToast('用户已删除并同步')}))}
function mdCell(v){return String(v??'').replace(/\|/g,'\\|').replace(/\n/g,'<br>')}function mdTable(h,rows){return `| ${h.map(mdCell).join(' | ')} |\n| ${h.map(()=> '---').join(' | ')} |\n`+rows.map(r=>`| ${r.map(mdCell).join(' | ')} |`).join('\n')}
function setExportScope(s){exportScope=s;refreshExportPreview()}function getExportRange(){const now=new Date();if(exportScope==='week'){const start=monday(now),end=new Date(start);end.setDate(start.getDate()+6);end.setHours(23,59,59,999);return{label:`本周数据 ${fmt(start)} 至 ${fmt(end)}`,start,end}}const [y,m]=($('exportMonth').value||`${now.getFullYear()}-${pad(now.getMonth()+1)}`).split('-').map(Number),start=new Date(y,m-1,1),end=new Date(y,m,0);end.setHours(23,59,59,999);return{label:`指定月份 ${y}年${m}月`,start,end}}
function buildMarkdownExport(){const u=currentUser(),r=getExportRange(),rs=records().filter(x=>{const d=new Date(x.date);return d>=r.start&&d<=r.end}).sort((a,b)=>(a.date+a.startTime).localeCompare(b.date+b.startTime)),total=sum(rs),summary=mdTable(['项目','数值'],[['导出范围',r.label],['导出时间',new Date().toLocaleString()],['用户名',u.username],['称号',titleFromExp(totalExpForUser(u.id))],['职业',u.role||'勇者'],['记录条数',rs.length],['合计时长',`${total}h`]]),detail=mdTable(['日期','开始时间','结束时间','加班时长(h)','类型','备注'],rs.map(r=>[r.date,r.startTime,r.endTime,r.duration,r.type,r.remark||'']));return `# 2F Overtime Dungeon 加班数据导出\n\n## 导出汇总\n\n${summary}\n\n## 加班记录明细\n\n${detail}\n`}
function refreshExportPreview(){['week','month'].forEach(s=>{const b=$(`exportScope_${s}`);if(b)b.classList.toggle('active',exportScope===s)});$('exportMonth').disabled=exportScope!=='month';$('exportText').value=buildMarkdownExport()}
function exportData(){const now=new Date();exportScope='week';$('exportMonth').value=`${now.getFullYear()}-${pad(now.getMonth()+1)}`;$('exportMask').classList.add('show');refreshExportPreview()}function closeExport(){$('exportMask').classList.remove('show')}
function exportFilename(){const u=currentUser(),tag=exportScope==='month'?$('exportMonth').value:'week',name=String(u?.username||'user').trim().replace(/[\\/:*?"<>|]+/g,'-').replace(/\s+/g,'-').slice(0,40)||'user';return `overtime-${name}-${tag}.md`}
function downloadExportMarkdown(){const a=document.createElement('a');a.href='data:text/markdown;charset=utf-8,'+encodeURIComponent(buildMarkdownExport());a.download=exportFilename();a.click();showToast('已生成 Markdown')}async function copyExportText(){try{await navigator.clipboard.writeText($('exportText').value);showToast('已复制 Markdown')}catch{$('exportText').select();document.execCommand('copy');showToast('已复制 Markdown')}}
function requestClear(){askConfirm('确认清空？','将删除当前用户所有加班记录。',()=>{const u=currentUser();runSync(()=>store.clearRecordsForUser(u.id),()=>{render();showToast('已清空并同步')})})}function logout(){askConfirm('确认退出登录？','退出后需要重新输入账号密码。',()=>{store.clearCurrentUser();page='login';render();showToast('已退出登录')})}
function renderTypeGrid(){$('typeGrid').innerHTML=types.map(t=>`<button class="${selectedType===t?'active':''}" onclick="pickType('${t}')">${t}</button>`).join('')}function pickType(t){selectedType=t;renderTypeGrid()}
function openSheet(date,id=''){const r=records().find(v=>v.id===id);$('sheetTitle').textContent=r?'编辑加班记录':'添加加班记录';$('editId').value=id;$('fDate').value=r?r.date:date;$('fStart').value=r?r.startTime:'';$('fEnd').value=r?r.endTime:'';$('fRemark').value=r?r.remark:'';selectedType=r?r.type:'设计';renderTypeGrid();$('formError').textContent='';updateDurationPreview();$('sheet').classList.add('show')}function closeSheet(){$('sheet').classList.remove('show')}function updateDurationPreview(){const v=duration($('fStart').value,$('fEnd').value);$('durationPreview').textContent=v?`${v}h`:'0h'}
async function saveRecord(btn){const u=currentUser(),id=$('editId').value,date=$('fDate').value,start=$('fStart').value,end=$('fEnd').value,du=duration(start,end);if(!date)return $('formError').textContent='请选择日期';if(!start||!end)return $('formError').textContent='请填写开始和结束时间';if(du<=0)return $('formError').textContent='结束时间必须晚于开始时间';const done=setBusyButton(btn,id?'更新中...':'保存中...'),old=allRecords().find(r=>r.id===id),payload={date,startTime:start,endTime:end,duration:du,type:selectedType,remark:$('fRemark').value.trim(),updatedAt:new Date().toISOString()},record=id&&old?{...old,...payload}:{id:uid('rec'),userId:u.id,...payload,createdAt:new Date().toISOString()},sync=store.saveRecord(record);closeSheet();render();showToast(id?'已更新，正在同步':'已添加，正在同步');try{await sync;render();showToast('已同步到飞书')}catch(e){done();render();showToast(e.message||'飞书保存失败')}}
boot()

